### ISSUE TITLE
Spring Boot Failure

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid-spring-boot#294]
Hi

I have used the sample VDB spring boot example and when i execute the jar i'm getting the below error.
I'm using Maven 3 and JDK 8

14:27:52.646 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: Unable to instantiate factory class [org.teiid.spring.autoconfigure.EnvironmentPropertiesPostProcessor] for factor
y type [org.springframework.boot.env.EnvironmentPostProcessor]
        at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:168)
        at org.springframework.core.io.support.SpringFactoriesLoader.loadFactories(SpringFactoriesLoader.java:104)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.loadPostProcessors(ConfigFileApplicationListener.java:193)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.j
ava:184)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.teiid.spring.example.Application.main(Application.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.UnsupportedClassVersionError: org/teiid/spring/autoconfigure/EnvironmentPropertiesPostProcessor has been compiled by a more recen
t version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)

**Comment by rareddy** [comment]
Try with JDK 11? https://www.baeldung.com/java-lang-unsupportedclassversion

**Comment by yapnel** [comment]
Yup, It requires JDK 11. Please kindly update the documentation to state the obvious. Thanks

btw, how do i set the username/password for authentication for JDBC?

**Comment by rareddy** [comment]
Thanks, I will update documents. Is there a particular one you were following?

By default there is no security defined, if one is needed then you would need to configure Keycloak for it.

**Comment by yapnel** [comment]
https://github.com/teiid/teiid-spring-boot/tree/master/samples/vdb

Do you have any guide for keycloak please?

**Comment by rareddy** [comment]
are you using this on OpenShift or standalone? On openshift I have this https://github.com/teiid/teiid-openshift-examples/tree/master/tutorial/02-secure-access-with-keycloak 

Standlone will be similar with same properties, right now we do not have guide for this
